export const STANDARD_MEASUREMENTS = [{
  size: 'Small',
  measurements: [
    {name: 'waist', value: 26.5},
    {name: 'highHip', value: 35},
    {name: 'lowHip', value: 37},
    {name: 'highHipDepth', value: 4.5},
    {name: 'lowHipDepth', value: 8.5},
    {name: 'skirtLength', value: 20},

    {name: 'neck', value: 14.5},
    {name: 'shoulder', value: 4.25},
    {name: 'frontLength', value: 15.5},
    {name: 'backLength', value: 17},
    {name: 'figureLength', value: 8.5},
    {name: 'figureBreadth', value: 8},
    {name: 'crossFront', value: 14},
    {name: 'crossBack', value: 15},
    {name: 'bust', value: 34},
    {name: 'upperBust', value: 33},
    {name: 'sideLength', value: 9},
    {name: 'armhole', value: 17},
  ],
}, {
  size: 'Medium',
  measurements: [
    {name: 'waist', value: 30},
    {name: 'highHip', value: 40},
    {name: 'lowHip', value: 43},
    {name: 'highHipDepth', value: 4.5},
    {name: 'lowHipDepth', value: 8.5},
    {name: 'skirtLength', value: 20},

    {name: 'neck', value: 14.5},
    {name: 'shoulder', value: 4.5},
    {name: 'frontLength', value: 15.75},
    {name: 'backLength', value: 17.25},
    {name: 'figureLength', value: 8.75},
    {name: 'figureBreadth', value: 8.5},
    {name: 'crossFront', value: 15.5},
    {name: 'crossBack', value: 16.5},
    {name: 'bust', value: 38},
    {name: 'upperBust', value: 36},
    {name: 'sideLength', value: 9},
    {name: 'armhole', value: 17},
  ],
}, {
  size: 'Large',
  measurements: [
    {name: 'waist', value: 34},
    {name: 'highHip', value: 44},
    {name: 'lowHip', value: 47},
    {name: 'highHipDepth', value: 4.5},
    {name: 'lowHipDepth', value: 8.5},
    {name: 'skirtLength', value: 20},

    {name: 'neck', value: 14.5},
    {name: 'shoulder', value: 4.5},
    {name: 'frontLength', value: 16},
    {name: 'backLength', value: 17.5},
    {name: 'figureLength', value: 9},
    {name: 'figureBreadth', value: 9},
    {name: 'crossFront', value: 16.5},
    {name: 'crossBack', value: 17.5},
    {name: 'bust', value: 42},
    {name: 'upperBust', value: 39},
    {name: 'sideLength', value: 9},
    {name: 'armhole', value: 17.5},
  ],
}];


export const MEASUREMENT_UNIT_OBJECTS = [{
  name: 'inch',
  asPlaceholder: 'Inches',
  asAbbreviation: 'in',
  perInch: 1,
}, {
  name: 'centimeter',
  asPlaceholder: 'Centimeters',
  asAbbreviation: 'cm',
  perInch: 2.54,
}];